### PR TITLE
BootStrap5 Update

### PR DESCRIPTION
**Pull request by ezrajrice**
Changes to MFA.html allows support of BootStrap 5 without breaking support for earlier versions of BootStrap.

### CODE REVIEW

**Comment by swainn** [comment]
@mkalioby any idea on when/if this will be merged?

**Comment by mkalioby** [comment]
I merged it in a new branch v2.5 and going to run the tests and release if all is good.

**Comment by swainn** [comment]
@mkalioby I'll take a look at that ASAP.

**Comment by swainn** [comment]
I reviewed the TOPT and Email options (as those are the ones we support in Tethys). Almost is functional with these two methods, with the exception of the delete button on the mfa table (see below). However, there are still a few bootstrap-version-related style issues. Examples below.

TOPT Start:

* Not centered
* Cancel button is unstyled

image

TOPT Auth Option:

* Not centered
* No margin between button and input field

image

Email Start Option:

* Not centered
* No margin between button and input field

image

Email Auth:

* Not centered
* No margin between button and input field

image

Select from multiple Auth methods screen:

* Not centered

image


Registration table:

* Table is in the center of page. Would be better to align top.
* Delete button is not displaying (Font Awesome icon no longer valid?)

image

**Comment by ezrajrice** [comment]
These should all be fixed with the latest commits. @swainn I can't find any reason in this repo for the registration table to be vertically centered. Is this possibly a Tethys issue?

**Comment by swainn** [comment]
> These should all be fixed with the latest commits. @swainn I can't find any reason in this repo for the registration table to be vertically centered. Is this possibly a Tethys issue?

Could be. I'll take a look and test with this branch.

**Comment by swainn** [comment]
@mkalioby this should be ready for you to test on bootstrap 3 and 4 again. Everything checks out for bootstrap 5 for the most part.

There are a few stylistic issues with the modal due to changes in bs5:

image

The order of the title and close button were reversed in bs 5 and instead of using `&times;` a `btn-close` class is used to add the "x". However, it is still functional in bs5, but it looks a little funny. Not really much we can do unless we have something like a bootstrap version variable to check.

The other change with modals is that to open them, you must call `$.modal('open')` instead of simply `$.modal()`. I left the `$.modal()` statements and added the `$.modal('open')` statements. Not sure if that will cause issues in bs 3 and 4, so test it out for sure.

**Comment by swainn** [comment]
@mkalioby I just pushed one more set of changes to this. I removed the empty `$.modal()` calls. It should work for all versions of bootstrap to use `$.modal('show')`, which I added in a previous commit.

**Comment by swainn** [comment]
@mkalioby I just tested the beta version of 2.5. It is looking great, but there are still a few unresolved issues:

* Delete buttons on the MFA table still are not appearing for Bootstrap 5. Including the classes `bi bi-trash` should fix it: 

image

* Even with the icons, the delete confirmation modal does not appear when clicking on the delete button. I'm not sure what is happening with that one. 

I wonder if you haven't merged the latest changes from this PR that have fixes for these things.

**Comment by mkalioby** [comment]
May be i missed that😕

**Comment by mkalioby** [comment]
This has been fixed for BS 4, please check
> @mkalioby this should be ready for you to test on bootstrap 3 and 4 again. Everything checks out for bootstrap 5 for the most part.
> 
> There are a few stylistic issues with the modal due to changes in bs5:
> 
> image
> 
> The order of the title and close button were reversed in bs 5 and instead of using `&times;` a `btn-close` class is used to add the "x". However, it is still functional in bs5, but it looks a little funny. Not really much we can do unless we have something like a bootstrap version variable to check.
> 
> The other change with modals is that to open them, you must call `$.modal('open')` instead of simply `$.modal()`. I left the `$.modal()` statements and added the `$.modal('open')` statements. Not sure if that will cause issues in bs 3 and 4, so test it out for sure.

**Comment by mkalioby** [comment]
> This has been fixed for BS 4, please check
> 
> > @mkalioby this should be ready for you to test on bootstrap 3 and 4 again. Everything checks out for bootstrap 5 for the most part.
> > There are a few stylistic issues with the modal due to changes in bs5:
> > image
> > The order of the title and close button were reversed in bs 5 and instead of using `&times;` a `btn-close` class is used to add the "x". However, it is still functional in bs5, but it looks a little funny. Not really much we can do unless we have something like a bootstrap version variable to check.
> > The other change with modals is that to open them, you must call `$.modal('open')` instead of simply `$.modal()`. I left the `$.modal()` statements and added the `$.modal('open')` statements. Not sure if that will cause issues in bs 3 and 4, so test it out for sure.

This shall be merged now on v2.5b2

**Comment by swainn** [comment]
@mkalioby I've tested our site with v2.5b2 and everything seems to be working well!

**Comment by mkalioby** [comment]
@swainn, v2.5 has been released on PyPi but I can't range issues when trying to release it on Conda, Can you please check.

**Pull request closed without merging**
